### ISSUE TITLE
Questions on progressive training and temporal information

### ISSUE THREAD

**Issue by minsujoo** [yixiao1/CILv2_multiview#4]
Hello, thank you for your excellent work! I have two questions about the dataset usage and temporal information:

1. In the paper, you mention dividing the dataset into Small Test Datasets, Single-Lane Towns, and Multi-Lane Towns. Did you train the model progressively, starting with simpler datasets and moving to more complex ones, or were all datasets used simultaneously? 

2. I noticed that g_conf.ENCODER_INPUT_FRAMES_NUM is set to 1 in the provided code, meaning the model only considers the current frame. Was this choice made because incorporating previous frames didn’t improve performance? If so, could you share more insights about the experiments or reasoning behind this decision?

Thank you for your insights!

**Comment by yixiao1** [comment]
Hi Minsu,

Thanks for your interest in our work.

1. The datasets are used simultaneously
2. Indeed, we believed that using more frames might improve the driving performance since they provide sequential information which is useful in autonomous driving. But due to the limited training resources and urgent timeline, we finally drop it. It will be a future work worthy of study.

Cheers
